# Generated by Django 5.2.16 on 2026-07-16 07:46

import django.core.validators
import django.db.models.deletion
import orders.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quality', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('PRODUCT_SPECIFICATIONS', '产品规格数据'), ('INTERNAL_ORDERS', '内部季度订单'), ('FACTORY_WORK_CONTACT', '生产工作联络单'), ('MATERIAL_ISSUE', '混料发料清单')], max_length=40)),
                ('parser', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PREVIEWED', '已预检'), ('COMMITTING', '导入中'), ('COMMITTED', '已导入'), ('FAILED', '失败')], db_index=True, default='PREVIEWED', max_length=20)),
                ('original_name', models.CharField(max_length=255)),
                ('original_file', models.FileField(upload_to=orders.models.business_import_path)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('errors', models.JSONField(default=list)),
                ('warnings', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='business_import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessRecordRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('PRODUCT_SPECIFICATION', '产品规格'), ('ORDER', '订单'), ('MATERIAL_RECEIPT', '胶料收料'), ('INSPECTION_CRITERION', '检验标准')], db_index=True, max_length=40)),
                ('record_id', models.PositiveBigIntegerField(db_index=True)),
                ('action', models.CharField(choices=[('CREATE', '新建'), ('IMPORT', '导入'), ('UPDATE', '修改'), ('DEACTIVATE', '停用')], max_length=20)),
                ('snapshot', models.JSONField(default=dict)),
                ('changes', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='business_record_revisions', to=settings.AUTH_USER_MODEL)),
                ('source_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='record_revisions', to='orders.businessimportbatch')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MaterialReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_no', models.CharField(db_index=True, max_length=100, verbose_name='订单号')),
                ('item_no', models.CharField(blank=True, default='', max_length=100, verbose_name='项次')),
                ('finished_product_name', models.CharField(blank=True, default='', max_length=300, verbose_name='成品品名')),
                ('specification', models.CharField(blank=True, default='', max_length=200, verbose_name='规格')),
                ('material', models.CharField(blank=True, default='', max_length=100, verbose_name='材质')),
                ('batch_no', models.CharField(blank=True, db_index=True, default='', max_length=150, verbose_name='批号')),
                ('sheet_size', models.CharField(blank=True, default='', max_length=100, verbose_name='出片尺寸')),
                ('weight_kg', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='重量(kg)')),
                ('manufactured_on', models.DateField(blank=True, db_index=True, null=True, verbose_name='制造日期')),
                ('source_sheet', models.CharField(blank=True, default='', max_length=100)),
                ('source_row', models.PositiveIntegerField(blank=True, null=True)),
                ('source_key', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material_receipts', to='quality.qualityorder')),
                ('source_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material_receipts', to='orders.businessimportbatch')),
            ],
            options={
                'ordering': ['-manufactured_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(blank=True, default='', max_length=200, verbose_name='产品名称')),
                ('customer_product_no', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='客户产品号')),
                ('specification', models.CharField(blank=True, default='', max_length=200, verbose_name='规格')),
                ('material', models.CharField(blank=True, default='', max_length=100, verbose_name='材质')),
                ('material_length', models.CharField(blank=True, default='', max_length=100, verbose_name='料长')),
                ('cut_weight', models.CharField(blank=True, default='', max_length=100, verbose_name='切料重')),
                ('strip_count', models.CharField(blank=True, default='', max_length=100, verbose_name='条数')),
                ('primary_curing', models.CharField(blank=True, default='', max_length=300, verbose_name='一次加硫条件')),
                ('secondary_curing', models.CharField(blank=True, default='', max_length=300, verbose_name='二次加硫条件')),
                ('total_cavities', models.CharField(blank=True, default='', max_length=100, verbose_name='总孔数')),
                ('effective_cavities', models.CharField(blank=True, default='', max_length=100, verbose_name='有效孔数')),
                ('mold_in_stock', models.CharField(blank=True, default='', max_length=100, verbose_name='模具在库')),
                ('mold_no', models.CharField(blank=True, default='', max_length=100, verbose_name='模具号')),
                ('mold_size', models.CharField(blank=True, default='', max_length=100, verbose_name='模具尺寸')),
                ('standard_hours', models.CharField(blank=True, default='', max_length=100, verbose_name='标准工时')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('normalized_key', models.CharField(blank=True, db_index=True, default='', max_length=500)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
                ('source_sheet', models.CharField(blank=True, default='', max_length=100)),
                ('source_row', models.PositiveIntegerField(blank=True, null=True)),
                ('source_key', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('source_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_specifications', to='orders.businessimportbatch')),
            ],
            options={
                'ordering': ['specification', 'material', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductInspectionCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_no', models.CharField(blank=True, default='', max_length=100, verbose_name='项次')),
                ('project_no', models.CharField(blank=True, default='', max_length=150, verbose_name='项目号')),
                ('customer', models.CharField(blank=True, default='', max_length=150, verbose_name='客户')),
                ('category', models.CharField(blank=True, default='', max_length=100, verbose_name='类别')),
                ('version', models.CharField(blank=True, default='', max_length=100, verbose_name='版本')),
                ('inspection_item', models.CharField(max_length=200, verbose_name='检验项目')),
                ('lower_limit', models.CharField(blank=True, default='', max_length=100, verbose_name='下限')),
                ('upper_limit', models.CharField(blank=True, default='', max_length=100, verbose_name='上限')),
                ('unit', models.CharField(blank=True, default='', max_length=100, verbose_name='单位')),
                ('source_sheet', models.CharField(blank=True, default='', max_length=100)),
                ('source_row', models.PositiveIntegerField(blank=True, null=True)),
                ('source_key', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inspection_criteria', to='quality.qualityorder')),
                ('source_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inspection_criteria', to='orders.businessimportbatch')),
                ('product_specification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspection_criteria', to='orders.productspecification')),
            ],
            options={
                'ordering': ['product_specification_id', 'category', 'inspection_item', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='businessimportbatch',
            index=models.Index(fields=['sha256', 'source_type'], name='business_import_sha_type_idx'),
        ),
        migrations.AddIndex(
            model_name='businessrecordrevision',
            index=models.Index(fields=['record_type', 'record_id', 'created_at'], name='business_revision_record_idx'),
        ),
        migrations.AddConstraint(
            model_name='materialreceipt',
            constraint=models.CheckConstraint(condition=models.Q(('weight_kg__gte', 0)), name='material_receipt_weight_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='materialreceipt',
            constraint=models.UniqueConstraint(condition=models.Q(('source_key', ''), _negated=True), fields=('source_key',), name='uniq_material_receipt_source_key'),
        ),
        migrations.AddConstraint(
            model_name='productspecification',
            constraint=models.UniqueConstraint(condition=models.Q(('source_key', ''), _negated=True), fields=('source_key',), name='uniq_product_spec_source_key'),
        ),
        migrations.AddConstraint(
            model_name='productinspectioncriterion',
            constraint=models.UniqueConstraint(condition=models.Q(('source_key', ''), _negated=True), fields=('source_key',), name='uniq_inspection_criterion_source_key'),
        ),
    ]
