# Generated by Django 5.2.16 on 2026-08-30 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_product_mold_model_and_receipt_issued_on'),
        ('quality', '0011_defectreason_processcardunitbinding_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, default='', max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('source', models.CharField(choices=[('MANUAL', '人工调整'), ('SHIPMENT', '出货联动'), ('CUSTOMER_RETURN', '退货联动'), ('IMPORT', '导入'), ('SYSTEM', '系统联动')], db_index=True, default='MANUAL', max_length=30)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_status_changes', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_changes', to='quality.qualityorder')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['order', 'created_at'], name='order_status_change_idx')],
            },
        ),
    ]
