# Generated by Django 5.2.16 on 2026-09-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderstatuschange'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspecification',
            name='actual_cut_weight',
            field=models.CharField(blank=True, default='', help_text='仅允许在ERP页面手工维护，业务文件导入不得覆盖。', max_length=100, verbose_name='实际切料重'),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='actual_material_length',
            field=models.CharField(blank=True, default='', help_text='仅允许在ERP页面手工维护，业务文件导入不得覆盖。', max_length=100, verbose_name='实际切料长'),
        ),
    ]
