# Generated by Django 5.2 on 2026-07-11

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("molds", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QualityEmployee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("employee_no", models.CharField(max_length=50, unique=True, verbose_name="员工编号")),
                ("name", models.CharField(max_length=100, verbose_name="姓名")),
                ("team", models.CharField(blank=True, max_length=100, verbose_name="班组")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("INSPECTOR", "品检员"),
                            ("REWORKER", "返工员"),
                            ("BOTH", "品检兼返工"),
                        ],
                        max_length=20,
                        verbose_name="岗位",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="在职/启用")),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
            ],
            options={"ordering": ["employee_no"]},
        ),
        migrations.CreateModel(
            name="QualityOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order_no", models.CharField(db_index=True, max_length=100, verbose_name="订单号")),
                ("batch_no", models.CharField(blank=True, default="", max_length=100, verbose_name="批次号")),
                ("product_code", models.CharField(blank=True, max_length=100, verbose_name="产品编号")),
                ("product_name", models.CharField(max_length=200, verbose_name="产品名称")),
                ("specification", models.CharField(max_length=200, verbose_name="规格")),
                ("material", models.CharField(max_length=100, verbose_name="材质/胶料")),
                (
                    "order_quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="订单数量",
                    ),
                ),
                ("order_date", models.DateField(db_index=True, verbose_name="下单日期")),
                ("due_date", models.DateField(blank=True, db_index=True, null=True, verbose_name="交期")),
                ("mold_size", models.CharField(blank=True, max_length=100, verbose_name="模具尺寸")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "进行中"),
                            ("COMPLETED", "已完成"),
                            ("CANCELLED", "已取消"),
                        ],
                        db_index=True,
                        default="OPEN",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quality_orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
            ],
            options={
                "ordering": ["-order_date", "-id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("order_quantity__gt", 0)),
                        name="quality_order_quantity_gt_zero_ck",
                    ),
                    models.UniqueConstraint(
                        fields=("order_no", "batch_no", "specification", "material"),
                        name="uniq_quality_order_batch_spec_material",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="QualityShipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("shipment_no", models.CharField(max_length=100, unique=True, verbose_name="出货单号")),
                ("shipment_date", models.DateField(db_index=True, verbose_name="出货日期")),
                ("inspection_quantity", models.PositiveIntegerField(verbose_name="质检数量")),
                ("qualified_quantity", models.PositiveIntegerField(default=0, verbose_name="合格数量")),
                ("defective_quantity", models.PositiveIntegerField(default=0, verbose_name="不良数量")),
                ("shipped_quantity", models.PositiveIntegerField(verbose_name="出货数量")),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quality_shipments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "inspector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inspected_shipments",
                        to="quality.qualityemployee",
                        verbose_name="品检员",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipments",
                        to="quality.qualityorder",
                        verbose_name="订单/批次",
                    ),
                ),
            ],
            options={
                "ordering": ["-shipment_date", "-id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("inspection_quantity__gt", 0)),
                        name="quality_shipment_inspection_gt_zero_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("shipped_quantity__gt", 0)),
                        name="quality_shipment_shipped_gt_zero_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "inspection_quantity",
                                models.F("qualified_quantity") + models.F("defective_quantity"),
                            )
                        ),
                        name="quality_shipment_inspection_balance_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("shipped_quantity__lte", models.F("qualified_quantity"))),
                        name="quality_shipment_shipped_lte_qualified_ck",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ReturnRework",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("rework_date", models.DateField(db_index=True, verbose_name="退货/返工日期")),
                (
                    "reason_category",
                    models.CharField(
                        choices=[
                            ("APPEARANCE", "外观"),
                            ("DIMENSION", "尺寸"),
                            ("MATERIAL", "材质"),
                            ("MIXED", "混料/混装"),
                            ("PACKAGING", "包装"),
                            ("OTHER", "其他"),
                        ],
                        db_index=True,
                        max_length=20,
                        verbose_name="原因分类",
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="具体原因")),
                ("returned_quantity", models.PositiveIntegerField(verbose_name="退货数量")),
                ("reworked_quantity", models.PositiveIntegerField(default=0, verbose_name="返工数量")),
                ("recovered_quantity", models.PositiveIntegerField(default=0, verbose_name="返工合格数量")),
                ("scrap_quantity", models.PositiveIntegerField(default=0, verbose_name="报废数量")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待处理"),
                            ("PROCESSING", "处理中"),
                            ("COMPLETED", "已完成"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "work_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                        verbose_name="返工工时",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quality_return_reworks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "responsible_inspector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="responsible_reworks",
                        to="quality.qualityemployee",
                        verbose_name="责任品检员",
                    ),
                ),
                (
                    "rework_employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="handled_reworks",
                        to="quality.qualityemployee",
                        verbose_name="返工处理员工",
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reworks",
                        to="quality.qualityshipment",
                        verbose_name="原出货记录",
                    ),
                ),
            ],
            options={
                "ordering": ["-rework_date", "-id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("returned_quantity__gt", 0)),
                        name="quality_rework_returned_gt_zero_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("reworked_quantity__lte", models.F("returned_quantity"))),
                        name="quality_reworked_lte_returned_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "recovered_quantity__lte",
                                models.F("reworked_quantity") - models.F("scrap_quantity"),
                            )
                        ),
                        name="quality_rework_result_lte_reworked_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("work_hours__gte", 0)),
                        name="quality_rework_hours_nonnegative_ck",
                    ),
                ],
            },
        ),
    ]
