# Generated by Django 5.2.16 on 2026-07-16 07:46

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('quality', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='qualityorder',
            name='uniq_quality_order_batch_spec_material',
        ),
        migrations.AddField(
            model_name='qualityorder',
            name='forming_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='成型工时'),
        ),
        migrations.AddField(
            model_name='qualityorder',
            name='item_no',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='项次'),
        ),
        migrations.AddField(
            model_name='qualityorder',
            name='legacy_shipment_text',
            field=models.TextField(blank=True, default='', verbose_name='原出货信息'),
        ),
        migrations.AddField(
            model_name='qualityorder',
            name='manual_received_material_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='手工已发胶料(kg)'),
        ),
        migrations.AddField(
            model_name='qualityorder',
            name='process_card_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='流程卡张数'),
        ),
        migrations.AddField(
            model_name='qualityorder',
            name='process_card_covered_quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='流程卡覆盖订单数量'),
        ),
        migrations.AddField(
            model_name='qualityorder',
            name='product_specification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.productspecification', verbose_name='产品规格资料'),
        ),
        migrations.AddField(
            model_name='qualityorder',
            name='production_required',
            field=models.BooleanField(blank=True, null=True, verbose_name='是否生产'),
        ),
        migrations.AddField(
            model_name='qualityorder',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='qualityorder',
            name='required_material_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='所需胶料(kg)'),
        ),
        migrations.AddField(
            model_name='qualityorder',
            name='source_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.businessimportbatch'),
        ),
        migrations.AddField(
            model_name='qualityorder',
            name='source_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='qualityorder',
            name='source_row',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qualityorder',
            name='source_sheet',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='qualityorder',
            name='material',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='材质/胶料'),
        ),
        migrations.AlterField(
            model_name='qualityorder',
            name='order_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='下单日期'),
        ),
        migrations.AlterField(
            model_name='qualityorder',
            name='product_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='产品名称'),
        ),
        migrations.AddConstraint(
            model_name='qualityorder',
            constraint=models.CheckConstraint(condition=models.Q(('forming_hours__isnull', True), ('forming_hours__gte', 0), _connector='OR'), name='quality_order_forming_hours_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='qualityorder',
            constraint=models.CheckConstraint(condition=models.Q(('required_material_kg__isnull', True), ('required_material_kg__gte', 0), _connector='OR'), name='quality_order_required_material_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='qualityorder',
            constraint=models.CheckConstraint(condition=models.Q(('manual_received_material_kg__isnull', True), ('manual_received_material_kg__gte', 0), _connector='OR'), name='quality_order_received_material_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='qualityorder',
            constraint=models.UniqueConstraint(condition=models.Q(('source_key', ''), _negated=True), fields=('source_key',), name='uniq_quality_order_source_key'),
        ),
    ]
