# Generated by Django 5.2.16 on 2026-08-14 03:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('molds', '0004_remove_moldasset_mold_status_location_consistent_and_more'),
        ('orders', '0003_product_mold_model_and_receipt_issued_on'),
        ('quality', '0003_qualityorder_import_identity_and_total_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductUnitWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sample_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='sample count')),
                ('sample_total_weight_g', models.DecimalField(blank=True, decimal_places=5, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='sample total weight (g)')),
                ('unit_weight_g', models.DecimalField(blank=True, decimal_places=5, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='finished unit weight (g)')),
                ('measured_on', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='measurement date')),
                ('backfill_reason', models.TextField(blank=True, default='', verbose_name='historical-entry reason')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_product_unit_weights', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('mold_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_unit_weights', to='molds.moldmodel', verbose_name='mold model')),
                ('product_specification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_unit_weights', to='orders.productspecification', verbose_name='product specification')),
            ],
            options={
                'ordering': ['-measured_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProcessCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card_no', models.CharField(max_length=150, unique=True, verbose_name='process card number')),
                ('source_item_no', models.CharField(blank=True, default='', max_length=100, verbose_name='source item number')),
                ('source_order_no', models.CharField(blank=True, default='', max_length=100, verbose_name='source order number')),
                ('product_name_snapshot', models.CharField(blank=True, default='', max_length=200, verbose_name='product name snapshot')),
                ('product_code_snapshot', models.CharField(blank=True, default='', max_length=100, verbose_name='product code snapshot')),
                ('formula_code_snapshot', models.CharField(blank=True, default='', max_length=100, verbose_name='formula code snapshot')),
                ('specification_snapshot', models.CharField(blank=True, default='', max_length=200, verbose_name='specification snapshot')),
                ('material_snapshot', models.CharField(blank=True, default='', max_length=100, verbose_name='material snapshot')),
                ('customer_snapshot', models.CharField(blank=True, default='', max_length=150, verbose_name='customer snapshot')),
                ('department_snapshot', models.CharField(blank=True, default='', max_length=150, verbose_name='department snapshot')),
                ('special_requirements', models.TextField(blank=True, default='', verbose_name='special requirements')),
                ('qr_text', models.CharField(blank=True, default='', max_length=500, verbose_name='QR text')),
                ('original_image', models.ImageField(blank=True, null=True, upload_to='quality/process_cards/%Y/%m/', verbose_name='original process-card image')),
                ('material_issue_weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='material issued (kg)')),
                ('reprint_count', models.PositiveIntegerField(default=0, verbose_name='reprint count')),
                ('demand_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='demand date')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='card quantity')),
                ('unit_weight_g', models.DecimalField(decimal_places=5, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='unit weight snapshot (g)')),
                ('sample_count_snapshot', models.PositiveIntegerField(blank=True, null=True)),
                ('sample_total_weight_g_snapshot', models.DecimalField(blank=True, decimal_places=5, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('measured_on_snapshot', models.DateField(blank=True, null=True)),
                ('mold_model_code_snapshot', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PARTIAL_SHIPPED', 'Partially shipped'), ('SHIPPED', 'Shipped'), ('CANCELLED', 'Cancelled')], db_index=True, default='OPEN', max_length=20, verbose_name='status')),
                ('received_on', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='received date')),
                ('backfill_reason', models.TextField(blank=True, default='', verbose_name='historical-entry reason')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_process_cards', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_process_cards', to='quality.qualityorder', verbose_name='order')),
                ('product_specification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_process_cards', to='orders.productspecification', verbose_name='product specification')),
                ('unit_weight_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_cards', to='quality.productunitweight', verbose_name='unit weight configuration')),
            ],
            options={
                'ordering': ['-received_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='QualityReworkCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case_no', models.CharField(blank=True, default='', max_length=100, unique=True, verbose_name='rework case number')),
                ('origin', models.CharField(choices=[('INTERNAL', 'Internal rework'), ('CUSTOMER_RETURN', 'Customer return')], db_index=True, default='INTERNAL', max_length=20, verbose_name='origin')),
                ('opened_on', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='opened date')),
                ('backfill_reason', models.TextField(blank=True, default='', verbose_name='historical-entry reason')),
                ('reason_category', models.CharField(choices=[('APPEARANCE', '外观'), ('DIMENSION', '尺寸'), ('MATERIAL', '材质'), ('MIXED', '混料/混装'), ('PACKAGING', '包装'), ('OTHER', '其他')], db_index=True, default='OTHER', max_length=20, verbose_name='reason category')),
                ('reason', models.TextField(blank=True, default='', verbose_name='reason')),
                ('affected_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='affected quantity')),
                ('affected_weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='affected weight (kg)')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PROCESSING', 'Processing'), ('WAITING_REINSPECTION', 'Waiting for reinspection'), ('COMPLETED', 'Completed'), ('SCRAPPED', 'Scrapped'), ('CANCELLED', 'Cancelled')], db_index=True, default='OPEN', max_length=30, verbose_name='status')),
                ('closed_on', models.DateField(blank=True, null=True, verbose_name='closed date')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_rework_cases', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('process_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rework_cases', to='quality.processcard', verbose_name='process card')),
                ('responsible_inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='weighted_rework_cases', to='quality.qualityemployee', verbose_name='responsible inspector')),
            ],
            options={
                'ordering': ['-opened_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='QualityReworkAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt_no', models.PositiveIntegerField(blank=True, null=True, verbose_name='attempt number')),
                ('attempt_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='attempt date')),
                ('backfill_reason', models.TextField(blank=True, default='', verbose_name='historical-entry reason')),
                ('input_quantity', models.PositiveIntegerField(default=0)),
                ('reworked_quantity', models.PositiveIntegerField(default=0)),
                ('recovered_quantity', models.PositiveIntegerField(default=0)),
                ('scrap_quantity', models.PositiveIntegerField(default=0)),
                ('input_weight_kg', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('reworked_weight_kg', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('recovered_weight_kg', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('scrap_weight_kg', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PROCESSING', 'Processing'), ('WAITING_REINSPECTION', 'Waiting for reinspection'), ('COMPLETED', 'Completed'), ('SCRAPPED', 'Scrapped'), ('CANCELLED', 'Cancelled')], db_index=True, default='PROCESSING', max_length=20, verbose_name='status')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_rework_attempts', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('rework_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='weighted_rework_attempts', to='quality.qualityemployee', verbose_name='rework employee')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='quality.qualityreworkcase', verbose_name='rework case')),
            ],
            options={
                'ordering': ['case_id', 'attempt_no', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QualityShipmentBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipment_no', models.CharField(blank=True, default='', max_length=100, unique=True, verbose_name='shipment batch number')),
                ('client_key', models.CharField(blank=True, default='', max_length=128, verbose_name='idempotency client key')),
                ('shipment_date', models.DateField(blank=True, db_index=True, default=django.utils.timezone.localdate, null=True, verbose_name='actual shipment date')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('VOID', 'Void')], db_index=True, default='DRAFT', max_length=20, verbose_name='status')),
                ('customer', models.CharField(blank=True, default='', max_length=150, verbose_name='customer')),
                ('delivery_info', models.TextField(blank=True, default='', verbose_name='delivery information')),
                ('backfill_reason', models.TextField(blank=True, default='', verbose_name='historical-entry reason')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_shipment_batches', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='weighted_shipment_batches', to='quality.qualityemployee', verbose_name='inspector')),
            ],
            options={
                'ordering': ['-shipment_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='QualityShipmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('net_weight_kg', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='net shipment weight (kg)')),
                ('piece_quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='optional piece quantity')),
                ('unit_weight_g_snapshot', models.DecimalField(blank=True, decimal_places=5, max_digits=14, null=True)),
                ('theoretical_weight_kg_snapshot', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('max_allowed_weight_kg_snapshot', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('notes', models.TextField(blank=True, default='', verbose_name='notes')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='quality.qualityshipmentbatch', verbose_name='shipment batch')),
                ('process_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipment_lines', to='quality.processcard', verbose_name='process card')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='qualityreworkcase',
            name='shipment_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rework_cases', to='quality.qualityshipmentline', verbose_name='shipment line'),
        ),
        migrations.AddIndex(
            model_name='processcard',
            index=models.Index(fields=['order', 'source_item_no'], name='quality_pro_order_i_a26532_idx'),
        ),
        migrations.AddIndex(
            model_name='processcard',
            index=models.Index(fields=['status', 'demand_date'], name='quality_pro_status_3d8fc2_idx'),
        ),
        migrations.AddConstraint(
            model_name='processcard',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='quality_process_card_quantity_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='processcard',
            constraint=models.CheckConstraint(condition=models.Q(('unit_weight_g__gt', 0)), name='quality_process_card_weight_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='qualityreworkattempt',
            constraint=models.UniqueConstraint(fields=('case', 'attempt_no'), name='quality_rework_case_attempt_unique'),
        ),
        migrations.AddConstraint(
            model_name='qualityreworkattempt',
            constraint=models.CheckConstraint(condition=models.Q(('input_quantity__gte', 0), ('reworked_quantity__lte', models.F('input_quantity')), ('recovered_quantity__lte', models.F('reworked_quantity')), ('scrap_quantity__lte', models.F('reworked_quantity'))), name='quality_rework_attempt_quantity_bounds'),
        ),
        migrations.AddConstraint(
            model_name='qualityshipmentbatch',
            constraint=models.UniqueConstraint(condition=models.Q(('client_key', ''), _negated=True), fields=('client_key',), name='quality_shipment_batch_client_key_uniq'),
        ),
        migrations.AddIndex(
            model_name='qualityreworkcase',
            index=models.Index(fields=['status', 'opened_on'], name='quality_qua_status_bc73fb_idx'),
        ),
        migrations.AddIndex(
            model_name='qualityreworkcase',
            index=models.Index(fields=['origin', 'opened_on'], name='quality_qua_origin_a173ee_idx'),
        ),
    ]
