# Generated by Django 5.2.16 on 2026-08-14 03:43

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0004_productunitweight_processcard_qualityreworkcase_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='processcard',
            name='quality_process_card_weight_gt_zero',
        ),
        migrations.AlterField(
            model_name='processcard',
            name='unit_weight_g',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='unit weight snapshot (g)'),
        ),
    ]
