# Generated by Django 5.2.16 on 2026-08-20 03:47

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def backfill_batch_inspectors(apps, schema_editor):
    Batch = apps.get_model("quality", "QualityShipmentBatch")
    through = Batch._meta.get_field("inspectors").remote_field.through
    batch_fk = next(
        field for field in through._meta.fields
        if field.remote_field and field.remote_field.model == Batch
    )
    employee_model = apps.get_model("quality", "QualityEmployee")
    employee_fk = next(
        field for field in through._meta.fields
        if field.remote_field and field.remote_field.model == employee_model
    )
    for batch in Batch.objects.exclude(inspector_id__isnull=True).iterator():
        through.objects.get_or_create(
            **{batch_fk.attname: batch.pk, employee_fk.attname: batch.inspector_id}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_product_mold_model_and_receipt_issued_on'),
        ('quality', '0005_remove_processcard_quality_process_card_weight_gt_zero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualityshipmentbatch',
            name='inspectors',
            field=models.ManyToManyField(blank=True, related_name='weighted_shipment_batches_many', to='quality.qualityemployee', verbose_name='inspectors'),
        ),
        migrations.AddField(
            model_name='qualityshipmentbatch',
            name='material_snapshot',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='material snapshot'),
        ),
        migrations.AddField(
            model_name='qualityshipmentbatch',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_shipment_batches', to='quality.qualityorder', verbose_name='order'),
        ),
        migrations.AddField(
            model_name='qualityshipmentbatch',
            name='pieces_per_batch',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='pieces per product batch'),
        ),
        migrations.AddField(
            model_name='qualityshipmentbatch',
            name='product_batch_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='product batch count'),
        ),
        migrations.AddField(
            model_name='qualityshipmentbatch',
            name='product_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='product name snapshot'),
        ),
        migrations.AddField(
            model_name='qualityshipmentbatch',
            name='product_specification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_shipment_batches', to='orders.productspecification', verbose_name='product specification'),
        ),
        migrations.AddField(
            model_name='qualityshipmentbatch',
            name='specification_snapshot',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='specification snapshot'),
        ),
        migrations.AddField(
            model_name='qualityshipmentbatch',
            name='unit_weight_g',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='unit weight snapshot (g)'),
        ),
        migrations.RunPython(backfill_batch_inspectors, migrations.RunPython.noop),
        migrations.AddField(
            model_name='qualityshipmentline',
            name='material_snapshot',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='material snapshot'),
        ),
        migrations.AddField(
            model_name='qualityshipmentline',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_shipment_lines', to='quality.qualityorder', verbose_name='order'),
        ),
        migrations.AddField(
            model_name='qualityshipmentline',
            name='pieces_per_batch',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='pieces per product batch'),
        ),
        migrations.AddField(
            model_name='qualityshipmentline',
            name='product_batch_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='product batch count'),
        ),
        migrations.AddField(
            model_name='qualityshipmentline',
            name='product_specification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quality_shipment_lines', to='orders.productspecification', verbose_name='product specification'),
        ),
        migrations.AddField(
            model_name='qualityshipmentline',
            name='specification_snapshot',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='specification snapshot'),
        ),
        migrations.AlterField(
            model_name='qualityshipmentline',
            name='process_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipment_lines', to='quality.processcard', verbose_name='process card'),
        ),
    ]
