# Generated by Django 5.2.16 on 2026-08-20 03:51

from django.db import migrations, models


def backfill_legacy_inspectors(apps, schema_editor):
    Shipment = apps.get_model("quality", "QualityShipment")
    through = Shipment._meta.get_field("inspectors").remote_field.through
    shipment_fk = next(
        field for field in through._meta.fields
        if field.remote_field and field.remote_field.model == Shipment
    )
    employee_model = apps.get_model("quality", "QualityEmployee")
    employee_fk = next(
        field for field in through._meta.fields
        if field.remote_field and field.remote_field.model == employee_model
    )
    for shipment in Shipment.objects.exclude(inspector_id__isnull=True).iterator():
        through.objects.get_or_create(
            **{shipment_fk.attname: shipment.pk, employee_fk.attname: shipment.inspector_id}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0006_qualityshipmentbatch_inspectors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualityshipment',
            name='inspectors',
            field=models.ManyToManyField(blank=True, related_name='legacy_inspected_shipments_many', to='quality.qualityemployee', verbose_name='品检员（多人）'),
        ),
        migrations.RunPython(backfill_legacy_inspectors, migrations.RunPython.noop),
    ]
