# Generated by Django 5.2.16 on 2026-08-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0009_whole_batch_customer_returns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualityreworkcase',
            name='reason_category',
            field=models.CharField(choices=[('APPEARANCE', '外观'), ('STICKING', '粘皮'), ('DIMENSION', '尺寸'), ('MATERIAL', '材质'), ('MIXED', '混料/混装'), ('PACKAGING', '包装'), ('OTHER', '其他')], db_index=True, default='OTHER', max_length=20, verbose_name='reason category'),
        ),
        migrations.AlterField(
            model_name='returnrework',
            name='reason_category',
            field=models.CharField(choices=[('APPEARANCE', '外观'), ('STICKING', '粘皮'), ('DIMENSION', '尺寸'), ('MATERIAL', '材质'), ('MIXED', '混料/混装'), ('PACKAGING', '包装'), ('OTHER', '其他')], db_index=True, max_length=20, verbose_name='原因分类'),
        ),
    ]
