# Generated by Django 5.2.16 on 2026-08-30 13:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


DEFAULT_REASONS = (
    ("STICKING", "粘皮"),
    ("FLASH", "毛边/飞边"),
    ("UNDERFILL", "缺胶"),
    ("BUBBLE", "气泡"),
    ("DIMENSION", "尺寸异常"),
    ("DEFORMATION", "变形"),
    ("VULCANIZATION", "硫化异常"),
    ("MATERIAL", "材质异常"),
    ("MIXED", "混料/混装"),
    ("QUANTITY", "数量异常"),
    ("PACKAGING", "包装问题"),
    ("OTHER", "其他"),
)


def seed_defect_reasons(apps, schema_editor):
    Reason = apps.get_model("quality", "DefectReason")
    for index, (code, name) in enumerate(DEFAULT_REASONS, start=1):
        Reason.objects.update_or_create(
            code=code,
            defaults={
                "name": name,
                "is_active": True,
                "is_system": True,
                "sort_order": index * 10,
            },
        )


def attach_legacy_primary_reasons(apps, schema_editor):
    Reason = apps.get_model("quality", "DefectReason")
    Case = apps.get_model("quality", "QualityReworkCase")
    mapping = {
        "STICKING": "STICKING",
        "DIMENSION": "DIMENSION",
        "MATERIAL": "MATERIAL",
        "MIXED": "MIXED",
        "PACKAGING": "PACKAGING",
        "OTHER": "OTHER",
        "APPEARANCE": "OTHER",
    }
    ids = dict(Reason.objects.values_list("code", "id"))
    for old_code, new_code in mapping.items():
        Case.objects.filter(
            primary_reason__isnull=True,
            reason_category=old_code,
        ).update(primary_reason_id=ids[new_code])


def populate_process_card_tracking_ids(apps, schema_editor):
    """Give every pre-existing physical card its own stable tracking id.

    ``AddField(default=uuid.uuid4)`` evaluates the callable only once while
    SQLite rebuilds a populated table.  Adding the field as nullable first and
    updating one row at a time prevents unrelated historical cards from being
    merged into the same return/replacement history.
    """

    ProcessCard = apps.get_model("quality", "ProcessCard")
    database_alias = schema_editor.connection.alias
    cards = ProcessCard.objects.using(database_alias)
    for card_id in cards.filter(tracking_id__isnull=True).values_list(
        "id", flat=True
    ).iterator():
        cards.filter(pk=card_id).update(tracking_id=uuid.uuid4())


def backfill_customer_return_rounds(apps, schema_editor):
    """Number preserved customer-return history per physical process card."""

    Case = apps.get_model("quality", "QualityReworkCase")
    database_alias = schema_editor.connection.alias
    cases = Case.objects.using(database_alias)
    cases.filter(origin="CUSTOMER_RETURN").update(is_current_return=False)

    current_card_id = None
    current_round = 0
    latest_case_id = None
    for case_id, process_card_id in (
        cases.filter(
            origin="CUSTOMER_RETURN",
            process_card_id__isnull=False,
        )
        .exclude(status="CANCELLED")
        .order_by("process_card_id", "opened_on", "id")
        .values_list("id", "process_card_id")
        .iterator()
    ):
        if process_card_id != current_card_id:
            if latest_case_id is not None:
                cases.filter(pk=latest_case_id).update(is_current_return=True)
            current_card_id = process_card_id
            current_round = 0
        current_round += 1
        cases.filter(pk=case_id).update(return_round=current_round)
        latest_case_id = case_id
    if latest_case_id is not None:
        cases.filter(pk=latest_case_id).update(is_current_return=True)


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0010_alter_qualityreworkcase_reason_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DefectReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.RunPython(seed_defect_reasons, migrations.RunPython.noop),
        migrations.CreateModel(
            name='ProcessCardUnitBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipment_unit_no', models.PositiveIntegerField()),
                ('piece_quantity', models.PositiveIntegerField()),
                ('net_weight_kg', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
            ],
            options={
                'ordering': ['shipment_batch_id', 'shipment_unit_no'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='qualityreworkcase',
            name='quality_active_return_batch_unit_uniq',
        ),
        migrations.AddField(
            model_name='processcard',
            name='replaces',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replaced_by', to='quality.processcard', verbose_name='replaces process card'),
        ),
        migrations.AddField(
            model_name='processcard',
            name='tracking_id',
            field=models.UUIDField(db_index=True, editable=False, null=True),
        ),
        migrations.RunPython(
            populate_process_card_tracking_ids,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='processcard',
            name='tracking_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='qualityreworkcase',
            name='date_is_approximate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qualityreworkcase',
            name='inspectors',
            field=models.ManyToManyField(blank=True, related_name='weighted_rework_cases_many', to='quality.qualityemployee'),
        ),
        migrations.AddField(
            model_name='qualityreworkcase',
            name='is_current_return',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='qualityreworkcase',
            name='return_round',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='customer return round'),
        ),
        migrations.RunPython(
            backfill_customer_return_rounds,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='processcard',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('PARTIAL_SHIPPED', 'Partially shipped'), ('SHIPPED', 'Shipped'), ('REPLACED', '已补卡替换'), ('CANCELLED', 'Cancelled')], db_index=True, default='OPEN', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='qualityreworkattempt',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('PROCESSING', 'Processing'), ('WAITING_REINSPECTION', 'Waiting for reinspection'), ('COMPLETED', 'Completed'), ('WAITING_REWORK', '待返工'), ('RESHIPPED', '已重新出货'), ('SCRAPPED', 'Scrapped'), ('CANCELLED', 'Cancelled')], db_index=True, default='PROCESSING', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='qualityreworkcase',
            name='opened_on',
            field=models.DateField(blank=True, db_index=True, default=django.utils.timezone.localdate, null=True, verbose_name='opened date'),
        ),
        migrations.AlterField(
            model_name='qualityreworkcase',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('PROCESSING', 'Processing'), ('WAITING_REINSPECTION', 'Waiting for reinspection'), ('COMPLETED', 'Completed'), ('WAITING_REWORK', '待返工'), ('RESHIPPED', '已重新出货'), ('SCRAPPED', 'Scrapped'), ('CANCELLED', 'Cancelled')], db_index=True, default='OPEN', max_length=30, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='qualityreworkcase',
            name='primary_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_rework_cases', to='quality.defectreason'),
        ),
        migrations.AddField(
            model_name='qualityreworkcase',
            name='secondary_reasons',
            field=models.ManyToManyField(blank=True, related_name='secondary_rework_cases', to='quality.defectreason'),
        ),
        migrations.AddConstraint(
            model_name='qualityreworkcase',
            constraint=models.UniqueConstraint(condition=models.Q(('origin', 'CUSTOMER_RETURN'), ('shipment_batch__isnull', False), ('shipment_unit_no__isnull', False), ('status__in', ['OPEN', 'PROCESSING', 'WAITING_REINSPECTION', 'WAITING_REWORK'])), fields=('shipment_batch', 'shipment_unit_no'), name='quality_active_return_batch_unit_uniq'),
        ),
        migrations.AddConstraint(
            model_name='qualityreworkcase',
            constraint=models.CheckConstraint(condition=models.Q(('return_round__isnull', True), ('return_round__gt', 0), _connector='OR'), name='quality_rework_return_round_gt_zero'),
        ),
        migrations.AddField(
            model_name='processcardunitbinding',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_process_card_unit_bindings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='processcardunitbinding',
            name='process_card',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='unit_binding', to='quality.processcard'),
        ),
        migrations.AddField(
            model_name='processcardunitbinding',
            name='shipment_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='process_card_bindings', to='quality.qualityshipmentbatch'),
        ),
        migrations.AddConstraint(
            model_name='processcardunitbinding',
            constraint=models.UniqueConstraint(fields=('shipment_batch', 'shipment_unit_no'), name='quality_card_binding_batch_unit_uniq'),
        ),
        migrations.AddConstraint(
            model_name='processcardunitbinding',
            constraint=models.CheckConstraint(condition=models.Q(('shipment_unit_no__gt', 0)), name='quality_card_binding_unit_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='processcardunitbinding',
            constraint=models.CheckConstraint(condition=models.Q(('piece_quantity__gt', 0)), name='quality_card_binding_piece_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='processcardunitbinding',
            constraint=models.CheckConstraint(condition=models.Q(('net_weight_kg__gt', 0)), name='quality_card_binding_weight_gt_zero'),
        ),
        migrations.RunPython(
            attach_legacy_primary_reasons,
            migrations.RunPython.noop,
        ),
    ]
