# Generated by Django 5.2.16 on 2026-08-31 11:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal, ROUND_HALF_UP
from django.db import migrations, models


def backfill_confirmed_shipment_allocations(apps, schema_editor):
    ShipmentLine = apps.get_model("quality", "QualityShipmentLine")
    ShipmentAllocation = apps.get_model(
        "quality", "QualityShipmentOrderAllocation"
    )
    rows = []
    lines = (
        ShipmentLine.objects.filter(batch__status="CONFIRMED")
        .select_related("order", "process_card__order")
        .order_by("id")
    )
    for line in lines.iterator():
        if ShipmentAllocation.objects.filter(shipment_line_id=line.pk).exists():
            continue
        order = line.order or (
            line.process_card.order if line.process_card_id else None
        )
        if order is None:
            # Preserve dirty legacy history instead of making the production
            # container unavailable during migration.  Runtime accounting has
            # an explicit fallback for confirmed lines without an allocation;
            # an operator can repair the missing order later without losing
            # the original shipment row.
            continue
        quantity = line.piece_quantity
        unit_weight = line.unit_weight_g_snapshot or (
            line.process_card.unit_weight_g if line.process_card_id else None
        )
        if quantity is None and unit_weight and line.net_weight_kg:
            quantity = int(
                (
                    Decimal(line.net_weight_kg)
                    * Decimal("1000")
                    / Decimal(unit_weight)
                ).quantize(Decimal("1"), rounding=ROUND_HALF_UP)
            )
        if not quantity or int(quantity) < 1:
            # The original row remains untouched and continues through the
            # rolling-upgrade fallback.  Never guess a fulfilment quantity.
            continue
        rows.append(
            ShipmentAllocation(
                shipment_line_id=line.pk,
                order_id=order.pk,
                sequence=1,
                piece_start=0,
                piece_end=int(quantity),
                piece_quantity=int(quantity),
                net_weight_kg=line.net_weight_kg,
                is_overflow=False,
                order_no_snapshot=order.order_no,
                item_no_snapshot=order.item_no,
                specification_snapshot=order.specification,
                material_snapshot=order.material,
            )
        )
    if rows:
        ShipmentAllocation.objects.bulk_create(rows, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0011_defectreason_processcardunitbinding_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityShipmentOrderAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField()),
                ('piece_start', models.PositiveIntegerField()),
                ('piece_end', models.PositiveIntegerField()),
                ('piece_quantity', models.PositiveIntegerField()),
                ('net_weight_kg', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('is_overflow', models.BooleanField(default=False)),
                ('order_no_snapshot', models.CharField(blank=True, default='', max_length=100)),
                ('item_no_snapshot', models.CharField(blank=True, default='', max_length=100)),
                ('specification_snapshot', models.CharField(blank=True, default='', max_length=200)),
                ('material_snapshot', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'ordering': ['shipment_line_id', 'sequence'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='qualityreturnallocation',
            name='quality_return_case_line_uniq',
        ),
        migrations.AddField(
            model_name='qualityshipmentorderallocation',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_shipment_allocations', to='quality.qualityorder'),
        ),
        migrations.AddField(
            model_name='qualityshipmentorderallocation',
            name='shipment_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_allocations', to='quality.qualityshipmentline'),
        ),
        migrations.AddField(
            model_name='qualityreturnallocation',
            name='shipment_order_allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_allocations', to='quality.qualityshipmentorderallocation'),
        ),
        migrations.AddConstraint(
            model_name='qualityreturnallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('shipment_order_allocation__isnull', True)), fields=('case', 'shipment_line'), name='quality_return_case_legacy_line_uniq'),
        ),
        migrations.AddConstraint(
            model_name='qualityreturnallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('shipment_order_allocation__isnull', False)), fields=('case', 'shipment_order_allocation'), name='quality_return_case_order_alloc_uniq'),
        ),
        migrations.AddConstraint(
            model_name='qualityshipmentorderallocation',
            constraint=models.UniqueConstraint(fields=('shipment_line', 'sequence'), name='quality_ship_alloc_line_sequence_uniq'),
        ),
        migrations.AddConstraint(
            model_name='qualityshipmentorderallocation',
            constraint=models.CheckConstraint(condition=models.Q(('piece_quantity__gt', 0)), name='quality_ship_alloc_piece_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='qualityshipmentorderallocation',
            constraint=models.CheckConstraint(condition=models.Q(('piece_end__gt', models.F('piece_start'))), name='quality_ship_alloc_piece_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='qualityshipmentorderallocation',
            constraint=models.CheckConstraint(condition=models.Q(('net_weight_kg__gt', 0)), name='quality_ship_alloc_weight_gt_zero'),
        ),
        migrations.RunPython(
            backfill_confirmed_shipment_allocations,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
