# Generated by Django 5.2.16 on 2026-09-01 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0012_shipment_order_allocations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityShipmentBatchRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('AMEND', '修订'), ('VOID', '作废')], db_index=True, max_length=20, verbose_name='action')),
                ('reason', models.TextField(verbose_name='reason')),
                ('before_snapshot', models.JSONField(default=dict, verbose_name='before snapshot')),
                ('after_snapshot', models.JSONField(default=dict, verbose_name='after snapshot')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='quality.qualityshipmentbatch', verbose_name='shipment batch')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_shipment_batch_revisions', to=settings.AUTH_USER_MODEL, verbose_name='operator')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
