# Generated by Django 5.2 on 2026-09-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quality", "0013_shipment_batch_revisions"),
    ]

    operations = [
        migrations.AddField(
            model_name="qualityemployee",
            name="quick_resolve_key",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=512,
                null=True,
                unique=True,
            ),
        ),
    ]
