# Generated by Django 5.2.16 on 2026-09-17 10:40

import django.db.models.deletion
from django.db import migrations, models


def backfill_reshipment_batches(apps, schema_editor):
    QualityReworkCase = apps.get_model('quality', 'QualityReworkCase')
    QualityShipmentBatch = apps.get_model('quality', 'QualityShipmentBatch')
    claimed = set(
        QualityReworkCase.objects.exclude(reshipment_batch_id=None).values_list(
            'reshipment_batch_id', flat=True
        )
    )
    for case in QualityReworkCase.objects.filter(
        status='RESHIPPED', reshipment_batch_id=None
    ).iterator():
        candidates = QualityShipmentBatch.objects.filter(
            status='CONFIRMED',
            lines__notes__contains=case.case_no,
        ).order_by('shipment_date', 'id').distinct()
        batch = next((item for item in candidates if item.pk not in claimed), None)
        if batch is None:
            continue
        QualityReworkCase.objects.filter(pk=case.pk).update(
            reshipment_batch_id=batch.pk
        )
        claimed.add(batch.pk)


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0014_qualityemployee_quick_resolve_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualityreworkcase',
            name='reshipment_batch',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_rework_case', to='quality.qualityshipmentbatch', verbose_name='本轮重新出货批次'),
        ),
        migrations.RunPython(
            backfill_reshipment_batches,
            migrations.RunPython.noop,
        ),
    ]
