# Generated by Django 5.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quality", "0015_qualityreworkcase_reshipment_batch"),
    ]

    operations = [
        migrations.AddField(
            model_name="qualityemployee",
            name="phone",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="手机号/联系电话"
            ),
        ),
        migrations.AddField(
            model_name="qualityemployee",
            name="production_enabled",
            field=models.BooleanField(default=False, verbose_name="可参与前端生产"),
        ),
        migrations.AlterField(
            model_name="qualityemployee",
            name="role",
            field=models.CharField(
                choices=[
                    ("PRODUCTION", "前端生产"),
                    ("INSPECTOR", "品检员"),
                    ("REWORKER", "返工员"),
                    ("BOTH", "品检兼返工"),
                ],
                max_length=20,
                verbose_name="岗位",
            ),
        ),
    ]
