# Generated by Django 5.2.16 on 2026-08-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualperformanceentry',
            name='reason_category',
            field=models.CharField(blank=True, choices=[('APPEARANCE', '外观'), ('STICKING', '粘皮'), ('DIMENSION', '尺寸'), ('MATERIAL', '材质'), ('MIXED', '混料/混装'), ('PACKAGING', '包装'), ('OTHER', '其他')], default='', max_length=20, verbose_name='不良原因分类'),
        ),
    ]
