# Generated by Django 5.2.16 on 2026-09-21 10:10

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0007_productspecification_strip_weights'),
        ('quality', '0016_qualityemployee_production_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_no', models.CharField(max_length=80, unique=True, verbose_name='库存批次号')),
                ('received_on', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='入库日期')),
                ('source_type', models.CharField(choices=[('OPENING', '期初盘点'), ('PRODUCTION_SURPLUS', '生产余量'), ('MANUAL', '手工入库'), ('OTHER', '其他')], default='MANUAL', max_length=30, verbose_name='入库来源')),
                ('source_note', models.CharField(blank=True, default='', max_length=500, verbose_name='来源说明')),
                ('quality_status', models.CharField(choices=[('WAITING', '待检'), ('PASSED', '已检合格'), ('FAILED', '不合格'), ('HOLD', '冻结')], db_index=True, default='WAITING', max_length=12, verbose_name='质量状态')),
                ('inspected_on', models.DateField(blank=True, null=True, verbose_name='检验日期')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_batches_inspected', to='quality.qualityemployee')),
            ],
            options={
                'ordering': ['-received_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='库位编码')),
                ('rack_code', models.CharField(db_index=True, max_length=20, verbose_name='货架编号')),
                ('rack_type', models.CharField(choices=[('LARGE', '大货架'), ('SMALL', '小货架'), ('FRIDGE', '冰箱')], max_length=12, verbose_name='货架类型')),
                ('level_no', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='层号')),
                ('position_no', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='位置号')),
                ('label', models.CharField(blank=True, default='', max_length=100, verbose_name='库位名称')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
                ('allows_basket', models.BooleanField(default=False, verbose_name='允许放筐')),
                ('allows_bag', models.BooleanField(default=True, verbose_name='允许放袋')),
            ],
            options={
                'ordering': ['rack_code', 'level_no', 'position_no', 'code'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('level_no__isnull', False), ('position_no__isnull', False)), fields=('rack_code', 'level_no', 'position_no'), name='inventory_location_rack_level_position_uniq')],
            },
        ),
        migrations.CreateModel(
            name='InventoryContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('container_code', models.CharField(max_length=80, unique=True, verbose_name='容器编号')),
                ('container_type', models.CharField(choices=[('BAG', '袋'), ('BASKET', '筐')], max_length=10, verbose_name='容器类型')),
                ('bag_count', models.PositiveIntegerField(default=1, verbose_name='袋数')),
                ('pieces_per_bag', models.PositiveIntegerField(blank=True, null=True, verbose_name='每袋数量')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='库存数量')),
                ('status', models.CharField(choices=[('ACTIVE', '在用'), ('EMPTY', '已空'), ('CLOSED', '已关闭')], db_index=True, default='ACTIVE', max_length=10, verbose_name='容器状态')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='containers', to='inventory.inventorybatch')),
                ('location', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_container', to='inventory.inventorylocation')),
            ],
            options={
                'ordering': ['batch_id', 'container_code'],
            },
        ),
        migrations.CreateModel(
            name='InventoryOutbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outbound_no', models.CharField(max_length=80, unique=True, verbose_name='出库单号')),
                ('shipment_ref', models.CharField(blank=True, default='', max_length=100, verbose_name='装车/出货参考号')),
                ('status', models.CharField(choices=[('CONFIRMED', '已确认'), ('VOID', '已作废')], db_index=True, default='CONFIRMED', max_length=12, verbose_name='状态')),
                ('note', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_outbounds', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_outbounds', to='quality.qualityorder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryOutboundLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='出库数量')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbound_lines', to='inventory.inventorycontainer')),
                ('outbound', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='inventory.inventoryoutbound')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_code', models.CharField(blank=True, db_index=True, default='', max_length=120, verbose_name='产品编号')),
                ('product_name', models.CharField(blank=True, default='', max_length=200, verbose_name='产品名称')),
                ('specification', models.CharField(blank=True, db_index=True, default='', max_length=200, verbose_name='规格')),
                ('material', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='材质')),
                ('unit_weight_g', models.DecimalField(blank=True, decimal_places=5, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00001'))], verbose_name='成品单重(g)')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('product_specification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_products', to='orders.productspecification')),
            ],
            options={
                'ordering': ['product_code', 'specification', 'id'],
            },
        ),
        migrations.AddField(
            model_name='inventorybatch',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='inventory.inventoryproduct'),
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('RECEIPT', '入库'), ('OUTBOUND', '出库'), ('MOVE', '移库'), ('ADJUST', '盘点调整'), ('QUALITY', '质量状态变更')], max_length=12, verbose_name='流水类型')),
                ('quantity', models.IntegerField(verbose_name='变动数量')),
                ('reason', models.CharField(blank=True, default='', max_length=500, verbose_name='原因')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='inventory.inventorybatch')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='inventory.inventorycontainer')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions', to=settings.AUTH_USER_MODEL)),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_inventory_transactions', to='inventory.inventorylocation')),
                ('outbound', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='inventory.inventoryoutbound')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_inventory_transactions', to='inventory.inventorylocation')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MaterialRemainder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.CharField(max_length=120, verbose_name='胶料材质')),
                ('weight_kg', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='剩余重量(kg)')),
                ('stored_on', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='入冰箱时间')),
                ('fridge_code', models.CharField(default='F01-冰箱', max_length=50, verbose_name='存放位置')),
                ('note', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_remainders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-stored_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MaterialRemainderUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weight_kg', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='使用重量(kg)')),
                ('note', models.CharField(blank=True, default='', max_length=500, verbose_name='使用说明')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_remainder_uses', to=settings.AUTH_USER_MODEL)),
                ('remainder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uses', to='inventory.materialremainder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='inventoryproduct',
            constraint=models.UniqueConstraint(condition=models.Q(('product_code__gt', ''), ('specification__gt', ''), _connector='OR'), fields=('product_code', 'specification', 'material'), name='inventory_product_identity_uniq'),
        ),
    ]
