# Generated by Django 5.2.16 on 2026-07-11 05:30

import django.db.models.deletion
import django.utils.timezone
import molds.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='机台编号')),
                ('name', models.CharField(max_length=100, verbose_name='机台名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='MoldModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='型号')),
                ('product_name', models.CharField(max_length=200, verbose_name='产品名称')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='加工方编号')),
                ('name', models.CharField(max_length=150, verbose_name='加工方名称')),
                ('contact', models.CharField(blank=True, max_length=100, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='电话')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='货架编号')),
                ('name', models.CharField(max_length=100, verbose_name='货架名称')),
                ('is_configured', models.BooleanField(default=False, verbose_name='已配置')),
                ('structure_locked', models.BooleanField(default=False, verbose_name='结构已锁定')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RackSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity_mode', models.PositiveSmallIntegerField(verbose_name='容量模式')),
                ('position_no', models.PositiveSmallIntegerField(verbose_name='位置号')),
                ('stack_level', models.PositiveSmallIntegerField(default=1, verbose_name='叠放层')),
                ('display_code', models.CharField(db_index=True, max_length=80, verbose_name='显示库位编码')),
                ('technical_code', models.CharField(max_length=100, unique=True, verbose_name='内部库位编码')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='禁放')),
                ('blocking_reason', models.CharField(blank=True, max_length=200, verbose_name='禁放原因')),
            ],
            options={
                'ordering': ['zone__level__rack__code', '-zone__level__level_no', 'zone__code', 'position_no', 'stack_level'],
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('STANDARD', '标准模板'), ('LEGACY', '旧台账')], max_length=20)),
                ('status', models.CharField(choices=[('PREVIEWED', '已预检'), ('COMMITTED', '已导入'), ('FAILED', '失败')], default='PREVIEWED', max_length=20)),
                ('original_name', models.CharField(max_length=255)),
                ('payload', models.JSONField(default=dict)),
                ('errors', models.JSONField(default=list)),
                ('warnings', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MoldAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_code', models.CharField(max_length=100, unique=True, verbose_name='模具编号')),
                ('main_image', models.ImageField(blank=True, upload_to=molds.models.mold_image_path, verbose_name='主图')),
                ('status', models.CharField(choices=[('IN_STOCK', '在库'), ('ON_MACHINE', '上机'), ('OUTSOURCED', '外出加工')], max_length=20, verbose_name='当前状态')),
                ('allows_stacking', models.BooleanField(default=False, verbose_name='允许在其上叠放')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('status_changed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='状态更新时间')),
                ('current_machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_molds', to='molds.machine')),
                ('mold_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='molds.moldmodel')),
                ('current_processor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_molds', to='molds.processor')),
                ('current_slot', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='occupant', to='molds.rackslot')),
            ],
            options={
                'ordering': ['asset_code'],
            },
        ),
        migrations.CreateModel(
            name='RackLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_no', models.PositiveSmallIntegerField(verbose_name='层号')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='molds.rack')),
            ],
            options={
                'ordering': ['rack__code', '-level_no'],
            },
        ),
        migrations.CreateModel(
            name='MoldMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', '新建'), ('PUTAWAY', '归位'), ('MOVE', '移库'), ('LOAD_MACHINE', '上机'), ('SEND_OUT', '外出加工')], max_length=20, verbose_name='操作')),
                ('from_status', models.CharField(blank=True, max_length=20, verbose_name='原状态')),
                ('to_status', models.CharField(choices=[('IN_STOCK', '在库'), ('ON_MACHINE', '上机'), ('OUTSOURCED', '外出加工')], max_length=20, verbose_name='新状态')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_from', to='molds.machine')),
                ('mold', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='molds.moldasset')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mold_movements', to=settings.AUTH_USER_MODEL)),
                ('to_machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_to', to='molds.machine')),
                ('from_processor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_from', to='molds.processor')),
                ('to_processor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_to', to='molds.processor')),
                ('from_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_from', to='molds.rackslot')),
                ('to_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_to', to='molds.rackslot')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RackZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='区域编码')),
                ('label', models.CharField(max_length=50, verbose_name='区域名称')),
                ('allowed_capacities', models.JSONField(default=list, verbose_name='允许容量')),
                ('capacity_mode', models.PositiveSmallIntegerField(verbose_name='当前容量')),
                ('supports_stacking', models.BooleanField(default=False, verbose_name='支持叠放')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='molds.racklevel')),
            ],
            options={
                'ordering': ['level__rack__code', '-level__level_no', 'code'],
            },
        ),
        migrations.AddField(
            model_name='rackslot',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='molds.rackzone'),
        ),
        migrations.AddConstraint(
            model_name='racklevel',
            constraint=models.UniqueConstraint(fields=('rack', 'level_no'), name='uniq_rack_level'),
        ),
        migrations.AddConstraint(
            model_name='moldasset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'IN_STOCK'), ('current_slot__isnull', False), ('current_machine__isnull', True), ('current_processor__isnull', True)), models.Q(('status', 'ON_MACHINE'), ('current_slot__isnull', True), ('current_machine__isnull', False), ('current_processor__isnull', True)), models.Q(('status', 'OUTSOURCED'), ('current_slot__isnull', True), ('current_machine__isnull', True), ('current_processor__isnull', False)), _connector='OR'), name='mold_status_location_consistent'),
        ),
        migrations.AddConstraint(
            model_name='rackzone',
            constraint=models.UniqueConstraint(fields=('level', 'code'), name='uniq_level_zone'),
        ),
        migrations.AddConstraint(
            model_name='rackslot',
            constraint=models.UniqueConstraint(fields=('zone', 'capacity_mode', 'position_no', 'stack_level'), name='uniq_zone_capacity_position_stack'),
        ),
        migrations.AddConstraint(
            model_name='rackslot',
            constraint=models.CheckConstraint(condition=models.Q(('stack_level__in', [1, 2])), name='slot_stack_level_1_or_2'),
        ),
    ]
