# Generated by Django 5.2.16 on 2026-07-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("molds", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rack",
            name="layout_version",
            field=models.PositiveSmallIntegerField(default=1, verbose_name="布局版本"),
        ),
        migrations.AddField(
            model_name="rackzone",
            name="stacking_enabled",
            field=models.BooleanField(default=False, verbose_name="启用叠放"),
        ),
    ]
