# Generated by Django 5.2.16 on 2026-07-13 03:55

from django.db import migrations, models


def clear_customer_return_processors(apps, schema_editor):
    MoldAsset = apps.get_model("molds", "MoldAsset")
    MoldAsset.objects.filter(status="OUTSOURCED").update(current_processor=None)


class Migration(migrations.Migration):

    dependencies = [
        ('molds', '0002_rack_layout_version_rackzone_stacking_enabled'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='moldasset',
            name='mold_status_location_consistent',
        ),
        migrations.AlterField(
            model_name='moldasset',
            name='status',
            field=models.CharField(choices=[('IN_STOCK', '在库'), ('ON_MACHINE', '上机'), ('OUTSOURCED', '客户收回')], max_length=20, verbose_name='当前状态'),
        ),
        migrations.AlterField(
            model_name='moldmovement',
            name='action',
            field=models.CharField(choices=[('CREATE', '新建'), ('PUTAWAY', '归位'), ('MOVE', '移库'), ('LOAD_MACHINE', '上机'), ('SEND_OUT', '客户收回')], max_length=20, verbose_name='操作'),
        ),
        migrations.AlterField(
            model_name='moldmovement',
            name='to_status',
            field=models.CharField(choices=[('IN_STOCK', '在库'), ('ON_MACHINE', '上机'), ('OUTSOURCED', '客户收回')], max_length=20, verbose_name='新状态'),
        ),
        migrations.RunPython(clear_customer_return_processors, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='moldasset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'IN_STOCK'), ('current_slot__isnull', False), ('current_machine__isnull', True), ('current_processor__isnull', True)), models.Q(('status', 'ON_MACHINE'), ('current_slot__isnull', True), ('current_machine__isnull', False), ('current_processor__isnull', True)), models.Q(('status', 'OUTSOURCED'), ('current_slot__isnull', True), ('current_machine__isnull', True), ('current_processor__isnull', True)), _connector='OR'), name='mold_status_location_consistent'),
        ),
    ]
