# Generated by Django 5.2.16 on 2026-07-13 06:45

import django.db.models.functions.text
from django.db import migrations, models
from django.utils import timezone


def release_legacy_inactive_locations(apps, schema_editor):
    MoldAsset = apps.get_model("molds", "MoldAsset")
    MoldAsset.objects.using(schema_editor.connection.alias).filter(
        is_active=False
    ).update(
        current_slot=None,
        current_machine=None,
        current_processor=None,
        status_changed_at=timezone.now(),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('molds', '0003_remove_moldasset_mold_status_location_consistent_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='moldasset',
            name='mold_status_location_consistent',
        ),
        migrations.AlterField(
            model_name='moldasset',
            name='asset_code',
            field=models.CharField(max_length=100, verbose_name='模具编号'),
        ),
        migrations.AlterField(
            model_name='moldmovement',
            name='action',
            field=models.CharField(choices=[('CREATE', '新建'), ('PUTAWAY', '归位'), ('MOVE', '移库'), ('LOAD_MACHINE', '上机'), ('SEND_OUT', '客户收回'), ('EDIT', '编辑'), ('DELETE', '删除')], max_length=20, verbose_name='操作'),
        ),
        migrations.RunPython(
            release_legacy_inactive_locations,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='moldasset',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('asset_code'), condition=models.Q(('is_active', True)), name='uniq_active_mold_asset_code_ci'),
        ),
        migrations.AddConstraint(
            model_name='moldasset',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_active', False), ('current_slot__isnull', True), ('current_machine__isnull', True), ('current_processor__isnull', True)), models.Q(('is_active', True), models.Q(models.Q(('status', 'IN_STOCK'), ('current_slot__isnull', False), ('current_machine__isnull', True), ('current_processor__isnull', True)), models.Q(('status', 'ON_MACHINE'), ('current_slot__isnull', True), ('current_machine__isnull', False), ('current_processor__isnull', True)), models.Q(('status', 'OUTSOURCED'), ('current_slot__isnull', True), ('current_machine__isnull', True), ('current_processor__isnull', True)), _connector='OR')), _connector='OR'), name='mold_status_location_consistent'),
        ),
    ]
