# Generated by Django 5.2.16 on 2026-08-30 13:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('molds', '0004_remove_moldasset_mold_status_location_consistent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moldasset',
            name='default_cavities',
            field=models.PositiveSmallIntegerField(blank=True, help_text='该字段属于每副实物模具；生产补录选择本模具时自动带出。', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='默认模具孔数'),
        ),
    ]
