# Generated by Django 5.2.16 on 2026-07-11 10:00

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('molds', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PREVIEWED', '已预检'), ('COMMITTED', '已导入'), ('FAILED', '失败')], default='PREVIEWED', max_length=20)),
                ('original_name', models.CharField(max_length=255)),
                ('payload', models.JSONField(default=dict)),
                ('errors', models.JSONField(default=list)),
                ('warnings', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='站位编号')),
                ('group', models.CharField(choices=[('A', 'A组'), ('B', 'B组'), ('C', 'C组')], max_length=1, verbose_name='机台组')),
                ('position_no', models.PositiveSmallIntegerField(verbose_name='组内编号')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('machine', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_station', to='molds.machine', verbose_name='关联机台')),
            ],
            options={
                'ordering': ['group', 'position_no'],
            },
        ),
        migrations.CreateModel(
            name='ProductionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_no', models.CharField(db_index=True, max_length=100, verbose_name='订单号')),
                ('specification', models.CharField(max_length=200, verbose_name='规格')),
                ('material', models.CharField(blank=True, max_length=100, verbose_name='材质')),
                ('order_quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='订单数量')),
                ('cavities', models.PositiveSmallIntegerField(default=6, validators=[django.core.validators.MinValueValidator(1)], verbose_name='模具孔数')),
                ('estimated_defect_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='预估不良率(%)')),
                ('planned_mold_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='计划生产模数')),
                ('compound_size', models.CharField(blank=True, max_length=100, verbose_name='胶料尺寸')),
                ('strip_weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='条重(kg)')),
                ('strips_per_batch', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='每批条数')),
                ('curing_seconds', models.PositiveIntegerField(default=0, verbose_name='硫化时间(秒)')),
                ('estimated_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='预计生产工时')),
                ('loaded_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='上模时间')),
                ('expected_change_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='预计换模时间')),
                ('unloaded_at', models.DateTimeField(blank=True, null=True, verbose_name='下机时间')),
                ('status', models.CharField(choices=[('PLANNED', '待上机'), ('RUNNING', '生产中'), ('COMPLETED', '已完成'), ('CANCELLED', '已取消')], db_index=True, default='PLANNED', max_length=20, verbose_name='生产状态')),
                ('operator', models.CharField(blank=True, max_length=100, verbose_name='作业员')),
                ('unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='产品单价')),
                ('material_unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='材料单价(元/kg)')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_runs', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('mold', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_runs', to='molds.moldasset', verbose_name='模具')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='production.productionstation', verbose_name='生产站位')),
            ],
            options={
                'ordering': ['-loaded_at', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductionDailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('production_date', models.DateField(db_index=True, verbose_name='生产日期')),
                ('operator', models.CharField(blank=True, max_length=100, verbose_name='作业员')),
                ('produced_mold_count', models.PositiveIntegerField(default=0, verbose_name='生产模数')),
                ('good_quantity', models.PositiveIntegerField(default=0, verbose_name='良品数量')),
                ('defective_quantity', models.PositiveIntegerField(default=0, verbose_name='不良数量')),
                ('material_kg', models.DecimalField(decimal_places=3, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='材料用量(kg)')),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='人工成本')),
                ('energy_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='能耗成本')),
                ('other_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='其他成本')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='production.productionrun', verbose_name='生产订单')),
            ],
            options={
                'ordering': ['production_date', 'id'],
                'constraints': [models.UniqueConstraint(fields=('run', 'production_date'), name='uniq_daily_log_per_run_date')],
            },
        ),
        migrations.AddConstraint(
            model_name='productionstation',
            constraint=models.UniqueConstraint(fields=('group', 'position_no'), name='uniq_production_group_position'),
        ),
        migrations.AddConstraint(
            model_name='productionstation',
            constraint=models.CheckConstraint(condition=models.Q(('position_no__gte', 1), ('position_no__lte', 6)), name='production_position_between_1_and_6'),
        ),
        migrations.AddConstraint(
            model_name='productionrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PLANNED', 'RUNNING'])), fields=('station',), name='uniq_active_run_per_station'),
        ),
        migrations.AddConstraint(
            model_name='productionrun',
            constraint=models.UniqueConstraint(condition=models.Q(('mold__isnull', False), ('status__in', ['PLANNED', 'RUNNING'])), fields=('mold',), name='uniq_active_run_per_mold'),
        ),
    ]
