# Generated by Django 5.2 on 2026-07-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productionimportbatch",
            name="status",
            field=models.CharField(
                choices=[
                    ("PREVIEWED", "已预检"),
                    ("COMMITTING", "导入中"),
                    ("COMMITTED", "已导入"),
                    ("FAILED", "失败"),
                ],
                default="PREVIEWED",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="productionrun",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        status="PLANNED",
                        loaded_at__isnull=True,
                        expected_change_at__isnull=True,
                        unloaded_at__isnull=True,
                    )
                    | models.Q(
                        status="RUNNING",
                        loaded_at__isnull=False,
                        unloaded_at__isnull=True,
                    )
                    | models.Q(
                        status="COMPLETED",
                        loaded_at__isnull=False,
                        unloaded_at__isnull=False,
                    )
                    | models.Q(
                        status="CANCELLED",
                        loaded_at__isnull=True,
                        expected_change_at__isnull=True,
                        unloaded_at__isnull=True,
                    )
                    | models.Q(
                        status="CANCELLED",
                        loaded_at__isnull=False,
                        unloaded_at__isnull=False,
                    )
                ),
                name="prod_run_status_time_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="productionrun",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(unloaded_at__isnull=True)
                    | models.Q(
                        loaded_at__isnull=False,
                        unloaded_at__gte=models.F("loaded_at"),
                    )
                ),
                name="prod_run_unload_order_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="productionrun",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(expected_change_at__isnull=True)
                    | models.Q(
                        loaded_at__isnull=False,
                        expected_change_at__gte=models.F("loaded_at"),
                    )
                ),
                name="prod_run_expected_order_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="productionrun",
            constraint=models.UniqueConstraint(
                fields=("station", "order_no"),
                name="uniq_run_station_order",
            ),
        ),
    ]
