# Generated by Django 5.2 on 2026-07-11

from decimal import Decimal

from django.conf import settings
from django.core.validators import MinValueValidator
from django.db import migrations, models
import django.db.models.deletion


def migrate_daily_accounting_to_settlement(apps, schema_editor):
    ProductionRun = apps.get_model("production", "ProductionRun")
    ProductionDailyLog = apps.get_model("production", "ProductionDailyLog")
    ProductionSettlementRevision = apps.get_model(
        "production", "ProductionSettlementRevision"
    )

    for run in ProductionRun.objects.all().iterator():
        logs = list(
            ProductionDailyLog.objects.filter(run_id=run.pk).order_by("pk")
        )
        if not logs:
            continue

        for log in logs:
            operator = " ".join(str(log.operator or run.operator or "未登记").split())
            log.operator = operator or "未登记"
            log.curing_seconds_snapshot = run.curing_seconds
            log.save(update_fields=["operator", "curing_seconds_snapshot"])

        run.actual_good_quantity = sum(log.legacy_good_quantity for log in logs)
        run.actual_defective_quantity = sum(
            log.legacy_defective_quantity for log in logs
        )
        run.total_material_kg = sum(
            (log.legacy_material_kg for log in logs), Decimal("0")
        )
        run.labor_cost = sum(
            (log.legacy_labor_cost for log in logs), Decimal("0")
        )
        run.energy_cost = sum(
            (log.legacy_energy_cost for log in logs), Decimal("0")
        )
        run.other_cost = sum(
            (log.legacy_other_cost for log in logs), Decimal("0")
        )
        eligible = run.status == "COMPLETED" or (
            run.status == "CANCELLED" and run.loaded_at is not None
        )
        if eligible:
            run.settled_at = run.unloaded_at
            run.settled_by_id = run.created_by_id
        run.save(
            update_fields=[
                "actual_good_quantity",
                "actual_defective_quantity",
                "total_material_kg",
                "labor_cost",
                "energy_cost",
                "other_cost",
                "settled_at",
                "settled_by",
            ]
        )
        if eligible:
            revision = ProductionSettlementRevision.objects.create(
                run_id=run.pk,
                revision_no=1,
                action="SETTLED",
                cavities=run.cavities,
                produced_mold_count=sum(log.produced_mold_count for log in logs),
                unit_price=run.unit_price,
                material_unit_price=run.material_unit_price,
                actual_good_quantity=run.actual_good_quantity,
                actual_defective_quantity=run.actual_defective_quantity,
                total_material_kg=run.total_material_kg,
                labor_cost=run.labor_cost,
                energy_cost=run.energy_cost,
                other_cost=run.other_cost,
                settlement_notes="由历史生产日报自动汇总迁移",
                changed_by_id=run.created_by_id,
            )
            if run.settled_at:
                ProductionSettlementRevision.objects.filter(pk=revision.pk).update(
                    changed_at=run.settled_at
                )


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0002_production_integrity_constraints"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="productiondailylog",
            name="uniq_daily_log_per_run_date",
        ),
        migrations.RenameField(
            model_name="productiondailylog",
            old_name="good_quantity",
            new_name="legacy_good_quantity",
        ),
        migrations.RenameField(
            model_name="productiondailylog",
            old_name="defective_quantity",
            new_name="legacy_defective_quantity",
        ),
        migrations.RenameField(
            model_name="productiondailylog",
            old_name="material_kg",
            new_name="legacy_material_kg",
        ),
        migrations.RenameField(
            model_name="productiondailylog",
            old_name="labor_cost",
            new_name="legacy_labor_cost",
        ),
        migrations.RenameField(
            model_name="productiondailylog",
            old_name="energy_cost",
            new_name="legacy_energy_cost",
        ),
        migrations.RenameField(
            model_name="productiondailylog",
            old_name="other_cost",
            new_name="legacy_other_cost",
        ),
        migrations.AddField(
            model_name="productiondailylog",
            name="curing_seconds_snapshot",
            field=models.PositiveIntegerField(
                default=0, editable=False, verbose_name="硫化时间快照(秒)"
            ),
        ),
        migrations.AlterField(
            model_name="productiondailylog",
            name="operator",
            field=models.CharField(max_length=100, verbose_name="作业员"),
        ),
        migrations.AlterField(
            model_name="productiondailylog",
            name="produced_mold_count",
            field=models.PositiveIntegerField(
                validators=[MinValueValidator(1)], verbose_name="生产模数"
            ),
        ),
        migrations.AlterField(
            model_name="productiondailylog",
            name="legacy_good_quantity",
            field=models.PositiveIntegerField(
                default=0, editable=False, verbose_name="历史良品数量"
            ),
        ),
        migrations.AlterField(
            model_name="productiondailylog",
            name="legacy_defective_quantity",
            field=models.PositiveIntegerField(
                default=0, editable=False, verbose_name="历史不良数量"
            ),
        ),
        migrations.AlterField(
            model_name="productiondailylog",
            name="legacy_material_kg",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                editable=False,
                max_digits=12,
                verbose_name="历史材料用量(kg)",
            ),
        ),
        migrations.AlterField(
            model_name="productiondailylog",
            name="legacy_labor_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                max_digits=14,
                verbose_name="历史人工成本",
            ),
        ),
        migrations.AlterField(
            model_name="productiondailylog",
            name="legacy_energy_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                max_digits=14,
                verbose_name="历史能耗成本",
            ),
        ),
        migrations.AlterField(
            model_name="productiondailylog",
            name="legacy_other_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                max_digits=14,
                verbose_name="历史其他成本",
            ),
        ),
        migrations.AddField(
            model_name="productionrun",
            name="actual_good_quantity",
            field=models.PositiveIntegerField(default=0, verbose_name="实际良品数量"),
        ),
        migrations.AddField(
            model_name="productionrun",
            name="actual_defective_quantity",
            field=models.PositiveIntegerField(default=0, verbose_name="实际不良数量"),
        ),
        migrations.AddField(
            model_name="productionrun",
            name="total_material_kg",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=14,
                validators=[MinValueValidator(Decimal("0"))],
                verbose_name="总材料用量(kg)",
            ),
        ),
        migrations.AddField(
            model_name="productionrun",
            name="labor_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=14,
                validators=[MinValueValidator(Decimal("0"))],
                verbose_name="人工成本",
            ),
        ),
        migrations.AddField(
            model_name="productionrun",
            name="energy_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=14,
                validators=[MinValueValidator(Decimal("0"))],
                verbose_name="能耗成本",
            ),
        ),
        migrations.AddField(
            model_name="productionrun",
            name="other_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=14,
                validators=[MinValueValidator(Decimal("0"))],
                verbose_name="其他成本",
            ),
        ),
        migrations.AddField(
            model_name="productionrun",
            name="settlement_notes",
            field=models.TextField(blank=True, verbose_name="结算备注"),
        ),
        migrations.AddField(
            model_name="productionrun",
            name="settled_at",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="结算时间"
            ),
        ),
        migrations.AddField(
            model_name="productionrun",
            name="settled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="settled_production_runs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="结算人",
            ),
        ),
        migrations.CreateModel(
            name="ProductionSettlementRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("revision_no", models.PositiveIntegerField(verbose_name="修订号")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("SETTLED", "结算"),
                            ("INVALIDATED", "日报变更后失效"),
                        ],
                        max_length=20,
                        verbose_name="操作",
                    ),
                ),
                ("cavities", models.PositiveSmallIntegerField(verbose_name="结算孔数")),
                (
                    "produced_mold_count",
                    models.PositiveIntegerField(verbose_name="累计生产模数"),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=4, max_digits=14, verbose_name="产品单价"
                    ),
                ),
                (
                    "material_unit_price",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=14,
                        verbose_name="材料单价(元/kg)",
                    ),
                ),
                (
                    "actual_good_quantity",
                    models.PositiveIntegerField(default=0, verbose_name="实际良品数量"),
                ),
                (
                    "actual_defective_quantity",
                    models.PositiveIntegerField(default=0, verbose_name="实际不良数量"),
                ),
                (
                    "total_material_kg",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=14,
                        verbose_name="总材料用量(kg)",
                    ),
                ),
                (
                    "labor_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="人工成本",
                    ),
                ),
                (
                    "energy_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="能耗成本",
                    ),
                ),
                (
                    "other_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="其他成本",
                    ),
                ),
                (
                    "settlement_notes",
                    models.TextField(blank=True, verbose_name="结算备注"),
                ),
                (
                    "changed_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="操作时间"
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="production_settlement_revisions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作人",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlement_revisions",
                        to="production.productionrun",
                        verbose_name="生产订单",
                    ),
                ),
            ],
            options={"ordering": ["-revision_no", "-id"]},
        ),
        migrations.RunPython(
            migrate_daily_accounting_to_settlement,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="productiondailylog",
            constraint=models.UniqueConstraint(
                fields=("run", "production_date", "operator"),
                name="uniq_daily_log_per_run_date_operator",
            ),
        ),
        migrations.AddConstraint(
            model_name="productiondailylog",
            constraint=models.CheckConstraint(
                condition=~models.Q(operator=""),
                name="prod_daily_operator_not_empty_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="productiondailylog",
            constraint=models.CheckConstraint(
                condition=models.Q(produced_mold_count__gte=1),
                name="prod_daily_molds_positive_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="productionsettlementrevision",
            constraint=models.UniqueConstraint(
                fields=("run", "revision_no"),
                name="uniq_production_settlement_revision",
            ),
        ),
    ]
