# Generated by Django 5.2.16 on 2026-07-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('molds', '0004_remove_moldasset_mold_status_location_consistent_and_more'),
        ('production', '0005_productionrun_material_changed_at'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productionstation',
            name='production_station_position_valid',
        ),
        migrations.AlterField(
            model_name='productionstation',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='机台编号'),
        ),
        migrations.AlterField(
            model_name='productionstation',
            name='group',
            field=models.CharField(max_length=20, verbose_name='机台组'),
        ),
        migrations.AlterField(
            model_name='productionstation',
            name='position_no',
            field=models.PositiveIntegerField(verbose_name='组内编号'),
        ),
        migrations.AddConstraint(
            model_name='productionstation',
            constraint=models.CheckConstraint(condition=models.Q(('position_no__gte', 1)), name='production_station_position_valid'),
        ),
    ]
