# Generated by Django 5.2.16 on 2026-08-30 13:09

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


def backfill_counter_ledger(apps, schema_editor):
    ProductionRun = apps.get_model("production", "ProductionRun")
    ProductionDailyLog = apps.get_model("production", "ProductionDailyLog")
    alias = schema_editor.connection.alias
    for run in ProductionRun.objects.using(alias).only("id", "cavities").iterator():
        cumulative = 0
        sequence = 0
        logs = ProductionDailyLog.objects.using(alias).filter(run_id=run.pk).order_by(
            "production_date", "id"
        )
        for log in logs.iterator():
            sequence += 1
            cumulative += int(log.produced_mold_count or 0)
            ProductionDailyLog.objects.using(alias).filter(pk=log.pk).update(
                sequence_no=sequence,
                counter_segment=1,
                cumulative_mold_count=cumulative,
                cavities_snapshot=max(int(run.cavities or 1), 1),
            )


class Migration(migrations.Migration):

    dependencies = [
        ('molds', '0005_moldasset_default_cavities'),
        ('orders', '0004_orderstatuschange'),
        ('production', '0007_productionrun_order_and_product_specification'),
        ('quality', '0011_defectreason_processcardunitbinding_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('is_active', models.BooleanField(default=True, verbose_name='在职/启用')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductionRecordAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', '新增'), ('UPDATED', '修改'), ('CANCELLED', '取消'), ('COUNTER_RESET', '计数清零'), ('PAUSED', '暂停'), ('RESUMED', '恢复')], max_length=30)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-changed_at', '-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='productiondailylog',
            options={'ordering': ['run_id', 'sequence_no', 'id']},
        ),
        migrations.RemoveConstraint(
            model_name='productiondailylog',
            name='uniq_daily_log_per_run_date_operator',
        ),
        migrations.RemoveConstraint(
            model_name='productionrun',
            name='uniq_active_run_per_station',
        ),
        migrations.RemoveConstraint(
            model_name='productionrun',
            name='uniq_active_run_per_mold',
        ),
        migrations.RemoveConstraint(
            model_name='productionrun',
            name='prod_run_status_time_ck',
        ),
        migrations.RemoveConstraint(
            model_name='productionrun',
            name='uniq_run_station_order',
        ),
        migrations.AddField(
            model_name='productiondailylog',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='取消时间'),
        ),
        migrations.AddField(
            model_name='productiondailylog',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_production_logs', to=settings.AUTH_USER_MODEL, verbose_name='取消人'),
        ),
        migrations.AddField(
            model_name='productiondailylog',
            name='cavities_snapshot',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='本次有效孔数快照'),
        ),
        migrations.AddField(
            model_name='productiondailylog',
            name='counter_segment',
            field=models.PositiveIntegerField(default=1, verbose_name='计数器分段'),
        ),
        migrations.AddField(
            model_name='productiondailylog',
            name='cumulative_mold_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='累计模数读数'),
        ),
        migrations.AddField(
            model_name='productiondailylog',
            name='defective_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='不良/报废数量'),
        ),
        migrations.AddField(
            model_name='productiondailylog',
            name='is_cancelled',
            field=models.BooleanField(db_index=True, default=False, verbose_name='已取消'),
        ),
        migrations.AddField(
            model_name='productiondailylog',
            name='sequence_no',
            field=models.PositiveIntegerField(default=0, verbose_name='交接顺序'),
        ),
        migrations.AddField(
            model_name='productiondailylog',
            name='shift',
            field=models.CharField(blank=True, choices=[('DAY', '白班'), ('NIGHT', '夜班')], max_length=10, verbose_name='班次'),
        ),
        migrations.AddField(
            model_name='productionrun',
            name='continuation_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='continuations', to='production.productionrun', verbose_name='接续的上一生产段'),
        ),
        migrations.AddField(
            model_name='productionrun',
            name='counter_segment',
            field=models.PositiveIntegerField(default=1, verbose_name='计数器分段'),
        ),
        migrations.AddField(
            model_name='productionrun',
            name='estimated_defect_mode',
            field=models.CharField(choices=[('RATE', '按比例'), ('QUANTITY', '按件数')], default='RATE', max_length=20, verbose_name='预估不良方式'),
        ),
        migrations.AddField(
            model_name='productionrun',
            name='estimated_defect_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='预估不良件数'),
        ),
        migrations.AddField(
            model_name='productionrun',
            name='pause_note',
            field=models.TextField(blank=True, verbose_name='暂停/恢复说明'),
        ),
        migrations.AddField(
            model_name='productionrun',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='暂停时间'),
        ),
        migrations.AddField(
            model_name='productionrun',
            name='segment_no',
            field=models.PositiveIntegerField(default=1, verbose_name='生产段序号'),
        ),
        migrations.AlterField(
            model_name='productiondailylog',
            name='production_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='生产日期'),
        ),
        migrations.AlterField(
            model_name='productionrun',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='production.productionstation', verbose_name='生产站位'),
        ),
        migrations.AlterField(
            model_name='productionrun',
            name='status',
            field=models.CharField(choices=[('PLANNED', '待上机'), ('RUNNING', '生产中'), ('PAUSED_ON_MACHINE', '暂停（模具保留在机台）'), ('PAUSED_UNLOADED', '暂停（已下机）'), ('COMPLETED', '已完成'), ('CANCELLED', '已取消')], db_index=True, default='PLANNED', max_length=20, verbose_name='生产状态'),
        ),
        migrations.AddConstraint(
            model_name='productionrun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('expected_change_at__isnull', True), ('loaded_at__isnull', True), ('status', 'PLANNED'), ('unloaded_at__isnull', True)), models.Q(('loaded_at__isnull', False), ('status', 'RUNNING'), ('unloaded_at__isnull', True)), models.Q(('loaded_at__isnull', False), ('status', 'PAUSED_ON_MACHINE'), ('unloaded_at__isnull', True)), models.Q(('loaded_at__isnull', False), ('status', 'PAUSED_UNLOADED'), ('unloaded_at__isnull', False)), models.Q(('loaded_at__isnull', False), ('status', 'COMPLETED'), ('unloaded_at__isnull', False)), models.Q(('expected_change_at__isnull', True), ('loaded_at__isnull', True), ('status', 'CANCELLED'), ('unloaded_at__isnull', True)), models.Q(('loaded_at__isnull', False), ('status', 'CANCELLED'), ('unloaded_at__isnull', False)), _connector='OR'), name='prod_run_status_time_ck'),
        ),
        migrations.AddConstraint(
            model_name='productionrun',
            constraint=models.UniqueConstraint(fields=('station', 'order_no', 'segment_no'), name='uniq_run_station_order'),
        ),
        migrations.AddConstraint(
            model_name='productionrun',
            constraint=models.UniqueConstraint(condition=models.Q(('station__isnull', False), ('status__in', ['PLANNED', 'RUNNING', 'PAUSED_ON_MACHINE'])), fields=('station',), name='uniq_active_run_per_station'),
        ),
        migrations.AddConstraint(
            model_name='productionrun',
            constraint=models.UniqueConstraint(condition=models.Q(('mold__isnull', False), ('status__in', ['PLANNED', 'RUNNING', 'PAUSED_ON_MACHINE'])), fields=('mold',), name='uniq_active_run_per_mold'),
        ),
        migrations.AddConstraint(
            model_name='productionemployee',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='uniq_production_employee_name_ci'),
        ),
        migrations.AddField(
            model_name='productiondailylog',
            name='assistant_operators',
            field=models.ManyToManyField(blank=True, related_name='assisted_production_logs', to='production.productionemployee', verbose_name='协助人员'),
        ),
        migrations.AddField(
            model_name='productiondailylog',
            name='operator_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_logs', to='production.productionemployee', verbose_name='主要作业员'),
        ),
        migrations.RunPython(backfill_counter_ledger, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='productiondailylog',
            constraint=models.UniqueConstraint(fields=('run', 'sequence_no'), name='uniq_prod_log_run_sequence'),
        ),
        migrations.AddField(
            model_name='productionrecordaudit',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_record_audits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productionrecordaudit',
            name='daily_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audits', to='production.productiondailylog'),
        ),
        migrations.AddField(
            model_name='productionrecordaudit',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='record_audits', to='production.productionrun'),
        ),
    ]
