# Generated by Django 5.2.16 on 2026-08-30 13:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('molds', '0005_moldasset_default_cavities'),
        ('orders', '0004_orderstatuschange'),
        ('production', '0008_productionemployee_productionrecordaudit_and_more'),
        ('quality', '0011_defectreason_processcardunitbinding_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productionrun',
            name='uniq_active_run_per_station',
        ),
        migrations.RemoveConstraint(
            model_name='productionrun',
            name='uniq_active_run_per_mold',
        ),
        migrations.AddField(
            model_name='productionrun',
            name='is_ledger_only',
            field=models.BooleanField(db_index=True, default=False, help_text='不占用实时机台或模具；用于历史纸质账及缺少现场状态的补录。', verbose_name='仅手工账补录'),
        ),
        migrations.AddConstraint(
            model_name='productionrun',
            constraint=models.UniqueConstraint(condition=models.Q(('is_ledger_only', False), ('station__isnull', False), ('status__in', ['PLANNED', 'RUNNING', 'PAUSED_ON_MACHINE'])), fields=('station',), name='uniq_active_run_per_station'),
        ),
        migrations.AddConstraint(
            model_name='productionrun',
            constraint=models.UniqueConstraint(condition=models.Q(('is_ledger_only', False), ('mold__isnull', False), ('status__in', ['PLANNED', 'RUNNING', 'PAUSED_ON_MACHINE'])), fields=('mold',), name='uniq_active_run_per_mold'),
        ),
    ]
