# Generated by Django 5.2.16 on 2026-08-30 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_remove_productionrun_uniq_active_run_per_station_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productiondailylog',
            name='prod_daily_operator_not_empty_ck',
        ),
    ]
