# Generated by Django 5.2.16 on 2026-08-30 13:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('molds', '0005_moldasset_default_cavities'),
        ('orders', '0004_orderstatuschange'),
        ('production', '0010_remove_productiondailylog_prod_daily_operator_not_empty_ck'),
        ('quality', '0011_defectreason_processcardunitbinding_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productionrun',
            name='prod_run_status_time_ck',
        ),
        migrations.AddConstraint(
            model_name='productionrun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('expected_change_at__isnull', True), ('loaded_at__isnull', True), ('status', 'PLANNED'), ('unloaded_at__isnull', True)), models.Q(('loaded_at__isnull', False), ('status', 'RUNNING'), ('unloaded_at__isnull', True)), models.Q(('loaded_at__isnull', False), ('status', 'PAUSED_ON_MACHINE'), ('unloaded_at__isnull', True)), models.Q(('loaded_at__isnull', False), ('status', 'PAUSED_UNLOADED'), ('unloaded_at__isnull', False)), models.Q(('is_ledger_only', True), ('status', 'COMPLETED')), models.Q(('is_ledger_only', False), ('loaded_at__isnull', False), ('status', 'COMPLETED'), ('unloaded_at__isnull', False)), models.Q(('expected_change_at__isnull', True), ('loaded_at__isnull', True), ('status', 'CANCELLED'), ('unloaded_at__isnull', True)), models.Q(('loaded_at__isnull', False), ('status', 'CANCELLED'), ('unloaded_at__isnull', False)), _connector='OR'), name='prod_run_status_time_ck'),
        ),
    ]
