# Generated by Django 5.2.16 on 2026-08-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0011_remove_productionrun_prod_run_status_time_ck_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productiondailylog',
            name='operator',
            field=models.CharField(blank=True, max_length=100, verbose_name='作业员'),
        ),
    ]
