# Generated by Django 5.2.16 on 2026-09-17 09:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def backfill_run_orders(apps, schema_editor):
    ProductionRun = apps.get_model('production', 'ProductionRun')
    ProductionRunOrder = apps.get_model('production', 'ProductionRunOrder')
    rows = []
    for run in ProductionRun.objects.exclude(order_id=None).select_related('order').iterator():
        rows.append(ProductionRunOrder(
            run_id=run.pk,
            order_id=run.order_id,
            planned_quantity=max(int(run.order_quantity or 0), 1),
            due_date_snapshot=run.order.due_date,
            sequence=1,
        ))
    ProductionRunOrder.objects.bulk_create(rows, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0012_alter_productiondailylog_operator'),
        ('quality', '0014_qualityemployee_quick_resolve_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionRunOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('planned_quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='本次计划数量')),
                ('due_date_snapshot', models.DateField(blank=True, null=True, verbose_name='交期快照')),
                ('sequence', models.PositiveIntegerField(default=1, verbose_name='显示顺序')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_run_links', to='quality.qualityorder', verbose_name='订单明细')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_links', to='production.productionrun', verbose_name='生产任务')),
            ],
            options={
                'ordering': ['due_date_snapshot', 'sequence', 'id'],
                'constraints': [models.UniqueConstraint(fields=('run', 'order'), name='uniq_production_run_order'), models.CheckConstraint(condition=models.Q(('planned_quantity__gt', 0)), name='production_run_order_quantity_gt_zero')],
            },
        ),
        migrations.RunPython(backfill_run_orders, migrations.RunPython.noop),
    ]
